name: Build & Release Binaries

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: wangyoucao577/go-release-action@v1.28
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "."
          binary_name: "ghostwriter-cli"
          ldflags: "-s -w -X 'github.com/GhostManager/Ghostwriter_CLI/cmd/config.Version=rolling' -X 'github.com/GhostManager/Ghostwriter_CLI/cmd/config.BuildDate=`date -u '+%d %b %Y'`'"
          release_tag: rolling
          overwrite: true
          executable_compression: upx --brute

      - name: Update Rolling Release
        uses: softprops/action-gh-release@v1
        with:
          name: Rolling Release (unstable)
          tag_name: rolling
          prerelease: true
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          body: |
            This is the rolling release of Ghostwriter CLI compiled from source (${{ github.sha }}).
            The repository updates releases automatically to keep them up-to-date with the `${{ github.ref_name }}` ${{ github.ref_type }}.
